/**
 * Maps ETF rows to a canonical underlying bucket and picks the most liquid symbol per bucket.
 */

export const GROUP_PREFERRED = {
  'NIFTY 50': ['NIFTYBEES', 'NIFTYETF', 'NIFTYIETF', 'SETFNIF50', 'NETF'],
  'NIFTY BANK': ['BANKBEES', 'BANKIETF', 'BANKETF', 'SETFNIFBK'],
  'NIFTY NEXT 50': ['JUNIORBEES', 'NEXT50IETF', 'SETFNN50'],
  'NIFTY 100': ['NIF100BEES', 'NIF100IETF'],
  'NIFTY IT': ['ITBEES', 'ITIETF', 'ITETF'],
  'NIFTY AUTO': ['AUTOBEES', 'AUTOIETF'],
  'NIFTY PHARMA': ['PHARMABEES'],
  'NIFTY PSU BANK': ['PSUBNKBEES', 'PSUBNKIETF'],
  'NIFTY PRIVATE BANK': ['SBIETFPB', 'PVTBANIETF'],
  'NIFTY INFRASTRUCTURE': ['INFRABEES', 'INFRAIETF'],
  'NIFTY INDIA CONSUMPTION': ['CONSUMBEES', 'CONSUMIETF'],
  'NIFTY FINANCIAL SERVICES': ['BFSI', 'FINIETF'],
  'NIFTY MIDCAP 150': ['MID150BEES', 'MIDCAPIETF', 'MIDCAPETF'],
  'NIFTY MIDCAP 100': ['MOM100'],
  'NIFTY SMALLCAP 250': ['MOSMALL250', 'HDFCSML250'],
  'BSE SENSEX': ['SENSEXETF', 'SENSEXIETF', 'BSLSENETFG'],
  'NIFTY 500': ['MONIFTY500', 'BSE500IETF'],
  'NIFTY 200 MOMENTUM 30': ['MOM30IETF', 'MOMOMENTUM', 'MOMENTUM'],
  'NIFTY 200 QUALITY 30': ['QUAL30IETF', 'NIFTYQLITY', 'SBIETFQLTY'],
  'NIFTY50 VALUE 20': ['NV20BEES', 'NV20IETF'],
  'NIFTY 100 LOW VOLATILITY 30': ['LOWVOLIETF', 'LOWVOL'],
  'CPSE': ['CPSEETF'],
  'BHARAT 22': ['ICICIB22'],
  'NASDAQ 100': ['MON100'],
  'HANG SENG': ['HNGSNGBEES'],
};

export const LIQUIDITY_RANK = {
  NIFTYBEES: 1000,
  BANKBEES: 990,
  JUNIORBEES: 980,
  ITBEES: 970,
  NIF100BEES: 960,
  PSUBNKBEES: 950,
  INFRABEES: 940,
  CPSEETF: 930,
  ICICIB22: 920,
  AUTOBEES: 910,
  PHARMABEES: 900,
  CONSUMBEES: 890,
  HNGSNGBEES: 850,
  MON100: 840,
  NV20BEES: 830,
  DIVOPPBEES: 820,
  SHARIABEES: 810,
  SNXT30BEES: 800,
  MID150BEES: 790,
  MANUFGBEES: 780,
  SETFNIF50: 760,
  SETFNIFBK: 750,
  SETFNN50: 740,
  SENSEXETF: 730,
  MONIFTY500: 720,
  MOM30IETF: 710,
  QUAL30IETF: 700,
  LOWVOLIETF: 690,
  BFSI: 670,
  MOSMALL250: 660,
  MOM100: 650,
  MULTICAP: 640,
  EMULTIMQ: 630,
  INTERNET: 610,
  EVINDIA: 600,
  METALIETF: 580,
  MOENERGY: 570,
  HEALTHIETF: 560,
  FMCGIETF: 550,
  OILIETF: 540,
  COMMOIETF: 530,
  ESG: 520,
  MASPTOP50: 510,
  MAFANG: 500,
  MSCIINDIA: 490,
};

const AMC_PREFIX = /^(NIPPON INDIA( ETF)?|ICICI PRUDENTIAL|ICICIPRAMC|MIRAE ASSET|MOTILAL OSWAL|HDFC|KOTAK|SBI(AMC)?|SBI MUTUAL FUND|UTI( MUTUAL FUND)?|DSP|ADITYA BIRLA SUN LIFE|BIRLA SUN LIFE|LIC MF|EDELWEISS|GROWW|ANGEL ONE|BARODA BNP PARIBAS|BAJAJ FINSERV|AXIS(AMC)?|AXISAMC|INVESCO INDIA|TATA|QUANTUM|ZERODHA|THE WEALTH COMPANY|UNION|CHOICE|360 ONE|BANDHAN)[\s-]*/i;

const SYMBOL_TO_UNDERLYING = {
  NIFTYBEES: 'NIFTY 50',
  BANKBEES: 'NIFTY BANK',
  JUNIORBEES: 'NIFTY NEXT 50',
  ITBEES: 'NIFTY IT',
  AUTOBEES: 'NIFTY AUTO',
  PHARMABEES: 'NIFTY PHARMA',
  PSUBNKBEES: 'NIFTY PSU BANK',
  INFRABEES: 'NIFTY INFRASTRUCTURE',
  CONSUMBEES: 'NIFTY INDIA CONSUMPTION',
  NIF100BEES: 'NIFTY 100',
  HNGSNGBEES: 'HANG SENG',
  NV20BEES: 'NIFTY50 VALUE 20',
  DIVOPPBEES: 'NIFTY DIVIDEND OPPORTUNITIES 50',
  SHARIABEES: 'NIFTY 50 SHARIAH',
  SNXT30BEES: 'BSE SENSEX NEXT 30',
  SNXT50BEES: 'BSE SENSEX NEXT 50',
  MID150BEES: 'NIFTY MIDCAP 150',
  MANUFGBEES: 'NIFTY INDIA MANUFACTURING',
  SETFNIF50: 'NIFTY 50',
  SETFNIFBK: 'NIFTY BANK',
  SETFNN50: 'NIFTY NEXT 50',
  NETF: 'NIFTY 50',
  MON100: 'NASDAQ 100',
  CPSEETF: 'CPSE',
  ICICIB22: 'BHARAT 22',
  BFSI: 'NIFTY FINANCIAL SERVICES',
  NIFTYETF: 'NIFTY 50',
  NIFTYIETF: 'NIFTY 50',
  NIFTYADD: 'NIFTY 50',
  NIFTYBETA: 'NIFTY 50',
  NIFTYBETF: 'NIFTY 50',
  NIFTYCASE: 'NIFTY 50',
  NIFTY1: 'NIFTY 50',
  BSLNIFTY: 'NIFTY 50',
  QNIFTY: 'NIFTY 50',
  AONENIFTY: 'NIFTY 50',
  ENIFTY: 'NIFTY 50',
  LICNETFN50: 'NIFTY 50',
  HDFCNIFTY: 'NIFTY 50',
  GROWWNIFTY: 'NIFTY 50',
  IVZINNIFTY: 'NIFTY 50',
  IDFNIFTYET: 'NIFTY 50',
  MOM50: 'NIFTY 50',
  BANKIETF: 'NIFTY BANK',
  BANKETF: 'NIFTY BANK',
  BANKADD: 'NIFTY BANK',
  BANKBETA: 'NIFTY BANK',
  BANKBETF: 'NIFTY BANK',
  BANKNIFTY1: 'NIFTY BANK',
  ABSLBANETF: 'NIFTY BANK',
  BBNPNBETF: 'NIFTY BANK',
  BNKETFAXIS: 'NIFTY BANK',
  EBANKNIFTY: 'NIFTY BANK',
  HDFCNIFBAN: 'NIFTY BANK',
  NEXT50IETF: 'NIFTY NEXT 50',
  NEXT50: 'NIFTY NEXT 50',
  NEXT50ETF: 'NIFTY NEXT 50',
  NEXT50BETA: 'NIFTY NEXT 50',
  NEXT50ADD: 'NIFTY NEXT 50',
  ABSLNN50ET: 'NIFTY NEXT 50',
  MONEXT50: 'NIFTY NEXT 50',
  HDFCNEXT50: 'NIFTY NEXT 50',
  GROWWNXT50: 'NIFTY NEXT 50',
  NIF100IETF: 'NIFTY 100',
  MONIFTY100: 'NIFTY 100',
  HDFCNIF100: 'NIFTY 100',
  LICNFNHGP: 'NIFTY 100',
  TOP100CASE: 'NIFTY 100',
  ITIETF: 'NIFTY IT',
  ITETF: 'NIFTY IT',
  ITADD: 'NIFTY IT',
  ITBETA: 'NIFTY IT',
  HDFCNIFIT: 'NIFTY IT',
  SBIETFIT: 'NIFTY IT',
  TECH: 'NIFTY IT',
  AUTOIETF: 'NIFTY AUTO',
  PSUBNKIETF: 'NIFTY PSU BANK',
  PSUBANK: 'NIFTY PSU BANK',
  PSUBANKADD: 'NIFTY PSU BANK',
  HDFCPSUBK: 'NIFTY PSU BANK',
  BANKPSU: 'NIFTY PSU BANK',
  SBIBPB: 'NIFTY PSU BANK',
  PVTBANIETF: 'NIFTY PRIVATE BANK',
  PVTBANKADD: 'NIFTY PRIVATE BANK',
  HDFCPVTBAN: 'NIFTY PRIVATE BANK',
  SBIETFPB: 'NIFTY PRIVATE BANK',
  NPBET: 'NIFTY PRIVATE BANK',
  INFRAIETF: 'NIFTY INFRASTRUCTURE',
  CONSUMIETF: 'NIFTY INDIA CONSUMPTION',
  CONSUMER: 'NIFTY INDIA CONSUMPTION',
  CONS: 'NIFTY INDIA CONSUMPTION',
  SBIETFCON: 'NIFTY INDIA CONSUMPTION',
  FINIETF: 'NIFTY FINANCIAL SERVICES EX-BANK',
  MIDCAPIETF: 'NIFTY MIDCAP 150',
  MIDCAPETF: 'NIFTY MIDCAP 150',
  MIDCAPADD: 'NIFTY MIDCAP 150',
  MIDCAPBETA: 'NIFTY MIDCAP 150',
  MID150: 'NIFTY MIDCAP 150',
  GROWWMC150: 'NIFTY MIDCAP 150',
  HDFCMID150: 'NIFTY MIDCAP 150',
  MOM100: 'NIFTY MIDCAP 100',
  LICNMID100: 'NIFTY MIDCAP 100',
  MOSMALL250: 'NIFTY SMALLCAP 250',
  HDFCSML250: 'NIFTY SMALLCAP 250',
  SMALLADD: 'NIFTY SMALLCAP 250',
  GROWWSC250: 'NIFTY SMALLCAP 250',
  SENSEXETF: 'BSE SENSEX',
  SENSEXIETF: 'BSE SENSEX',
  BSLSENETFG: 'BSE SENSEX',
  SENSEXBETA: 'BSE SENSEX',
  ESENSEX: 'BSE SENSEX',
  SENSEXADD: 'BSE SENSEX',
  LICNETFSEN: 'BSE SENSEX',
  MONIFTY500: 'NIFTY 500',
  BSE500IETF: 'NIFTY 500',
  HDFCBSE500: 'NIFTY 500',
  MOM30IETF: 'NIFTY 200 MOMENTUM 30',
  MOMOMENTUM: 'NIFTY 200 MOMENTUM 30',
  MOMENTUM: 'NIFTY 200 MOMENTUM 30',
  HDFCMOMENT: 'NIFTY 200 MOMENTUM 30',
  QUAL30IETF: 'NIFTY 200 QUALITY 30',
  NIFTYQLITY: 'NIFTY 200 QUALITY 30',
  SBIETFQLTY: 'NIFTY 200 QUALITY 30',
  NV20IETF: 'NIFTY50 VALUE 20',
  NV20: 'NIFTY50 VALUE 20',
  HDFCVALUE: 'NIFTY50 VALUE 20',
  LOWVOLIETF: 'NIFTY 100 LOW VOLATILITY 30',
  LOWVOL: 'NIFTY 100 LOW VOLATILITY 30',
  LOWVOL1: 'NIFTY 100 LOW VOLATILITY 30',
  HDFCLOWVOL: 'NIFTY 100 LOW VOLATILITY 30',
};

function cleanName(name) {
  return String(name || '')
    .toUpperCase()
    .replace(AMC_PREFIX, '')
    .replace(/\s+-\s+(GROWTH|IDCW)$/i, '')
    .replace(/\s+(ETF|BEES)\b.*$/i, '')
    .replace(/\s+EXCHANGE TRADED FUND.*$/i, '')
    .replace(/\s+/g, ' ')
    .trim();
}

export function underlyingKey(row) {
  const sym = String(row.tradingsymbol || '').toUpperCase();
  if (SYMBOL_TO_UNDERLYING[sym]) return SYMBOL_TO_UNDERLYING[sym];
  const cleaned = cleanName(row.name);
  return cleaned || sym;
}

export function liquidityScore(row) {
  const sym = String(row.tradingsymbol || '').toUpperCase();
  if (LIQUIDITY_RANK[sym] != null) return LIQUIDITY_RANK[sym];
  if (sym.endsWith('BEES')) return 500;
  return 0;
}

export function pickBestInGroup(rows, key) {
  if (!rows.length) return null;
  const preferred = GROUP_PREFERRED[key];
  if (preferred) {
    for (const sym of preferred) {
      const match = rows.find((row) => row.tradingsymbol.toUpperCase() === sym);
      if (match) return match;
    }
  }
  return [...rows].sort((a, b) => {
    const scoreDelta = liquidityScore(b) - liquidityScore(a);
    if (scoreDelta !== 0) return scoreDelta;
    return a.tradingsymbol.localeCompare(b.tradingsymbol);
  })[0];
}

export function dedupeEquityEtfs(rows) {
  const groups = new Map();
  rows.forEach((row) => {
    const key = underlyingKey(row);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(row);
  });

  const picked = [];
  groups.forEach((items, key) => {
    const best = pickBestInGroup(items, key);
    if (best) picked.push(best);
  });

  return picked.sort((a, b) => {
    const scoreDelta = liquidityScore(b) - liquidityScore(a);
    if (scoreDelta !== 0) return scoreDelta;
    return a.tradingsymbol.localeCompare(b.tradingsymbol);
  });
}
